name: Earthly CI

#This tells the workflow to trigger when a PR is merged to main branch
on:
  pull_request:
    branches: [ main ]
    types: [closed]


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      FORCE_COLOR: 1
    steps:
    - uses: actions/checkout@v3
    - name: Put back the git branch into git (Earthly uses it for tagging)
      run: |
        branch=""
        if [ -n "$GITHUB_HEAD_REF" ]; then
          branch="$GITHUB_HEAD_REF"
        else
          branch="${GITHUB_REF##*/}"
        fi
        git checkout -b "$branch" || true
    - name: Docker Login
      run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"
    #Download Earthly on runner
    - name: Download latest earthly
      run: earthly/actions-setup@v1
      with:
        version: 0.6.1
    - name: Earthly version
      run: earthly --version
    #Specify your own earthly command
    - name: Run test
      run: earthly +test
    - name: Run build
      run: earthly --ci --push +build